<!doctype html>
<html lang="en">

<a type="submit" href="/logout" id="item-1-button">Logout</a>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS -->
    <link rel="stylesheet" href="style.css">

    <!-- FONT AWESOME CDN  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous" />

    <title>Currency Converter using JavaScript - @code.scientist x @codingtorque</title>
</head>

<body>
<!-- Further Code Here -->

<div class="wrapper">
    <h2>Currency Converter</h2>
    <form action="/response" method="post">
        <div class="amount">
            <p>Enter Amount</p>
            <input type="text" name="quantity" value="1">
        </div>
        <div class="drop-list">
            <div class="from">
                <p>From</p>
                <div class="select-box">
                    <select name = 'from_currency'>
                        <?php foreach ($fromCurrency as $request): ?>
                            <option value=<?php echo $request['from_currency']; ?>><?php echo $request['from_currency']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="icon"><i class="fas fa-exchange-alt"></i></div>
            <div class="to">
                <p>To</p>
                <div class="select-box">
                    <select name = 'to_currency'>
                        <?php foreach ($toCurrency as $request): ?>
                            <option value=<?php echo $request['to_currency']; ?>><?php echo $request['to_currency']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="exchange-rate">Getting exchange rate...</div>
        <button>Get Exchange Rate</button>
    </form>
</div>

</body>

</html>

<style>
    /* Import Google Font - Poppins */
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap");

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: "Poppins", sans-serif;
    }

    body {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        padding: 0 10px;
        background: #1a212d;
    }

    .wrapper {
        width: 30rem;
        padding: 30px;
        border-radius: 7px;
        background: #161922;
        color: white;
        box-shadow: 7px 7px 20px rgba(0, 0, 0, 0.05);
    }

    .wrapper h2 {
        font-size: 28px;
        font-weight: 500;
        text-align: center;
    }

    .wrapper form {
        margin: 40px 0 20px 0;
    }

    form :where(input, select, button) {
        width: 100%;
        outline: none;
        border-radius: 5px;
        border: none;
    }

    form p {
        font-size: 18px;
        margin-bottom: 5px;
    }

    form input {
        height: 50px;
        font-size: 17px;
        padding: 0 15px;
        background: transparent;
        color: white;
        border: 1px solid #999;
    }

    form input:focus {
        padding: 0 14px;
        border: 2px solid #675afe;
    }

    form .drop-list {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-between;
        margin-top: 20px;
    }

    .from {
        width: 100%;
    }

    .to {
        width: 100%;
    }

    .drop-list .select-box {
        display: flex;
        width: 100%;
        height: 45px;
        align-items: center;
        border-radius: 5px;
        padding: 0 20px;
        border: 1px solid #999;
        background: #20232c;
    }

    .select-box img {
        max-width: 21px;
    }

    .select-box select {
        width: 100%;
        font-size: 16px;
        background: none;
        margin: 0 -5px 0 5px;
        color: white;
        background: #20232c;
    }

    .select-box select::-webkit-scrollbar {
        width: 8px;
    }

    .select-box select::-webkit-scrollbar-track {
        background: #fff;
    }

    .select-box select::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 8px;
        border-right: 2px solid #ffffff;
    }

    .drop-list .icon {
        cursor: pointer;
        margin-top: 10px;
        font-size: 22px;
        transform: rotate(90deg);
    }

    form .exchange-rate {
        font-size: 17px;
        margin: 20px 0 30px;
    }

    form button {
        height: 52px;
        color: #fff;
        font-size: 17px;
        cursor: pointer;
        background: #20232c;
        transition: 0.3s ease;
    }
</style>
